language: python
python:
- 3.6
before_install:
- wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
- chmod +x miniconda.sh
- "./miniconda.sh -b"
- export PATH=/home/travis/miniconda3/bin:$PATH
- conda update --yes conda
- git clone https://github.com/bw4sz/keras-retinanet.git
install:
- conda env create --file=environment.yml
- source activate DeepForest
- cd keras-retinanet
- pip install .
- python setup.py build_ext --inplace
- cd ..
env: TRAVIS=true
script:
- pytest --ignore=keras-retinanet/
deploy:
  provider: pypi
  user: bw4sz
  password:
    secure: k63dvwV2y+p2SVsGMsv3muN/emC+U/nNpXnVw2vgTVaHsKnIPkJA0maEk1/kGyFP5C5UPsE3JlJAkakawQEUSqx3OBSjn4WePBp9fTOJBcJ35etLkXd2BKUo0YNEf1vK5T7aFRTGdjVjj6cvMcblQtQTx4zKLbSle397dYGxYY5neVqogNRJN/f0B1+mXG/HiDtaumyRg/3brGclPHWYNrQW3smu9DLyEZIhF83PUsfFskdAqsQrYQ/eWKQKiCElkVAVG19FZqyhchH3MwIBSBpJnkl8FzKiMAMqwAdn5Abao9K4UQW1OBkR8gJlEkJQTOslijD11nl9+0vmbX2/EYh47LfFK08jv5+qtC63Bh54zrLiEpXU8lrhiQG+4HZ8CAT7MCd0r/yrqLgzM5BcB5B2qX8vKR4dVOv1GO0ufC6qv0+V06IBWbJEcQxw9w07Q0I6HxwHhQJLcajumyXFl55351Gpf18JNlaIbIpY2VIfLIGKC4WnDYRcBIeL1ylJ2wRcfW1FCXUb26fBE0SSEt/uKInQQjUtFjuP98InEnyFGQ0S/PTEknsx5ZNKMdFoygarLd2pzRGVuobbFBo3tFJbEn1vK8XTGG3qC5+MAViHtWF98q2cjBHJQdjh3mj6iPJCFKvVaZtBOZL60sJWfKpVsmh0fs7AjaoKFIYTRRE=
  on:
    tags: true
