language: python
python:
- 3.6
before_install:
- wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
- chmod +x miniconda.sh
- "./miniconda.sh -b"
- export PATH=/home/travis/miniconda3/bin:$PATH
- conda update --yes conda
- conda config --set always_yes yes --set changeps1 no
- conda update --yes conda
- conda install conda-build

install:
- conda env create --file=environment.yml
- source activate DeepForest
- python setup.py build_ext --inplace
env: TRAVIS=true
script:
- pytest --ignore=keras-retinanet/
# Build and Test conda package
- conda build conda_recipe/meta.yaml -c conda-forge -c defaults
