language: python
python:
    - "3.6"
before_install:
    - sudo apt-get update -q
    - sudo apt-get install gcc  unzip g++ git cmake -y
install:
    - pip install -r requirements.txt
    #laspy dependencies
    - ./install_dependencies.sh
    
# command to run tests
script:
    - pytest 