#Config file for DeepMeerkat train.py on HiPerGator

#SlidingWindow
patch_size: 400
patch_overlap: 0.05
rgb_res: 0.1

#Preprocessing routines
preprocess:
          zero_area: True

#Training
training_csvs: /home/b.weinstein/TreeSegmentation/analysis/Results/detection_boxes/SJER/2018/
rgb_tile_dir: /ufrc/ewhite/b.weinstein/NeonData/SJER/DP3.30010.001/2018/FullSite/D17/2018_SJER_3/L3/Camera/Mosaic/V01/
training_images: All
snapshot: /orange/ewhite/b.weinstein/retinanet/snapshots/20181005_134715/resnet50_04.h5
batch_size: 5      
epochs: 14
save_snapshot_path: /orange/ewhite/b.weinstein/retinanet/snapshots/
backbone: resnet50
shuffle_training: True
single_tile: False
score_threshold: 0.15

#Evaluation
evaluation_site: SJER
evaluation_images: 50
evaluation_tile_dir: /ufrc/ewhite/b.weinstein/NeonData/SJER/DP3.30010.001/2018/FullSite/D17/2018_SJER_3/L3/Camera/Mosaic/V01/
save_image_path: /orange/ewhite/b.weinstein/retinanet/snapshots/
shuffle_eval: False

#Ground truth
#Path, passed to glob for wildcards
itc_path: /home/b.weinstein/TreeSegmentation/data/ITCs/*/*.shp
itc_tile_path: /home/b.weinstein/TreeSegmentation/data/2017/Camera/L3/

#Non-max suppression, threshold for the IoU value to determine when a box should be suppressed.
nms_threshold: 0.1
