#Config file for DeepMeerkat train.py on hypergator

#Location of bound box csv
bbox_data_dir: data/
#/home/b.weinstein/TreeSegmentation/analysis/Results/bounding_boxes/

#Subsample dataset
subsample: None

rgb_tile_dir: data/
#/orange/ewhite/b.weinstein/NEON/D03/OSBS/DP1.30010.001/2017/FullSite/D03/2017_OSBS_3/L3/Camera/Mosaic/V01/
rgb_res: 0.1

#Debug plot image
plot_image: False

#Preprocessing routines
preprocess:
          zero_area: True
          NDVI: False
          NDVI_Threshold: 0.1

batch_size: 1      
