#Config file for DeepMeerkat train.py on hypergator

#Location of bound box csv
bbox_data_dir: /home/b.weinstein/TreeSegmentation/analysis/Results/detection_boxes/
rgb_tile_dir: /orange/ewhite/b.weinstein/NEON/D03/OSBS/DP1.30010.001/2017/FullSite/D03/2017_OSBS_3/L3/Camera/Mosaic/V01/

#bbox_data_dir: data/
#rgb_tile_dir: data/

#Subsample dataset
subsample: 200

rgb_res: 0.1

#Debug plot image
plot_image: False

#Preprocessing routines
preprocess:
          zero_area: True
          NDVI: False
          NDVI_Threshold: 0.1

#Training
snapshot: /orange/ewhite/b.weinstein/retinanet/snapshots/resnet50_onthefly_10.h5
batch_size: 1      
epochs: 50
evaluation_file: data/training/evaluation.csv
evaluation_tile_dir: data/
snapshot_path: /orange/ewhite/b.weinstein/retinanet/snapshots/