#Config file for DeepMeerkat train.py on local OSX

#SlidingWindow
patch_size: 400
patch_overlap: 0.05
rgb_res: 0.1

#Preprocessing routines
preprocess:
          zero_area: True

#Training
training_images: 2
training_csvs: data/SJER/
rgb_tile_dir: data/SJER/
snapshot: None
batch_size: 1      
epochs: 2
save_snapshot_path: None
backbone: resnet50
shuffle_training: True
single_tile: True
score_threshold: 0.2

#LIDAR
lidar_path: data/SJER/

#Evaluation
evaluation_site: SJER
evaluation_images: 3
evaluation_tile_dir: data/SJER/
save_image_path: snapshots/images/
shuffle_eval: False

#Non-max suppression, threshold for the IoU value to determine when a box should be suppressed.
nms_threshold: 0.15

#For hand annotation neon_MAP
validation_percent: 5

