#Debug config file for DeepMeerkat train_retinanet.py
#Running locally on Mac OSX

#Location of bound box csv
bbox_data_dir: data/

#evaluation dataset

#Subsample dataset
subsample: None

rgb_tile_dir: data/
rgb_res: 0.1

#Debug plot image
plot_image: False

#Preprocessing routines
preprocess:
          zero_area: True
          NDVI: False
          NDVI_Threshold: 0.1

#Training
snapshot: None
batch_size: 1     
epochs: 3
evaluation_file: data/training/evaluation.csv
evaluation_tile_dir: data/
snapshot_path: None

