#Config file for DeepMeerkat train.py on hypergator

#SlidingWindow
patch_size: 400
patch_overlap: 0.05
rgb_res: 0.1

#Debug plot image
plot_image: False

#Preprocessing routines
preprocess:
          zero_area: True
          NDVI: False
          NDVI_Threshold: 0.1

#Training
training_csvs: /home/b.weinstein/TreeSegmentation/analysis/Results/detection_boxes/OSBS/
rgb_tile_dir: /orange/ewhite/b.weinstein/NEON/D03/OSBS/DP1.30010.001/2017/FullSite/D03/2017_OSBS_3/L3/Camera/Mosaic/V01/
#rgb_tile_dir: /orange/ewhite/NeonData/SJER/DP1.30010.001/2017/FullSite/D17/2017_SJER_2/L3/Camera/Mosaic/V02/

#Number of sliding windows to select
subsample: 5000
snapshot: None
batch_size: 1      
epochs: 10
save_snapshot_path: None
backbone: resnet50
shuffle_training: True

#Evaluation
evaluation_csvs: data/NEON_D03_OSBS_DP1_407000_3291000_classified_point_cloud_laz.csv
#evaluation_csvs: /home/b.weinstein/TreeSegmentation/analysis/Results/detection_boxes/OSBS/

#Number of sliding windows to select for evaluation
validation_subsample: 50
evaluation_tile_dir: data/
#evaluation_tile_dir: /orange/ewhite/NeonData/SJER/DP1.30010.001/2017/FullSite/D17/2017_SJER_2/L3/Camera/Mosaic/V02/
save_image_path: snapshots/
shuffle_eval: True

#Non-max suppression, threshold for the IoU value to determine when a box should be suppressed.
nms_threshold: 0.5   
