#Config file for DeepMeerkat train.py on local OSX

#Data generation
num_hipergator_workers: 20
h5_dir: /Users/Ben/Downloads/

#SlidingWindow
patch_size: 400
patch_overlap: 0.05
rgb_res: 0.1

#Preprocessing routines
preprocess:
          zero_area: True

#Training
training_images: 2
training_csvs: /Users/Ben/Documents/DeepLidar/data/TEAK/
rgb_tile_dir: /Users/Ben/Documents/DeepLidar/data/TEAK/
snapshot: None
batch_size: 1   
epochs: 2
save_snapshot_path: None
backbone: resnet50
shuffle_training: False
score_threshold: 0.2

#Evaluation
evaluation_site: TEAK
evaluation_images: 3
evaluation_tile_dir: /Users/Ben/Documents/DeepLidar/data/TEAK/
save_image_path: snapshots/images/
shuffle_evaluation: False

#Non-max suppression, threshold for the IoU value to determine when a box should be suppressed.
nms_threshold: 0.15

#For hand annotation neon_MAP
validation_percent: 5

#LIDAR
lidar_path: /Users/Ben/Documents/DeepLidar/data/TEAK/
kernel_size: None
workers: 1
use_multiprocessing: False
max_queue_size: 10