#Config file for DeepMeerkat train.py on local OSX

#SlidingWindow
patch_size: 250
patch_overlap: 0.05
rgb_res: 0.1

#Debug plot image
plot_image: True

#Preprocessing routines
preprocess:
          zero_area: True
          NDVI: False
          NDVI_Threshold: 0.1

#Training
training_csvs: data/
rgb_tile_dir: data/
subsample: 4
snapshot: None
batch_size: 1      
epochs: 2
save_snapshot_path: snapshots/
backbone: resnet50

#Evaluation
evaluation_csvs: data/NEON_D03_OSBS_DP1_411000_3282000_classified_point_cloud_laz.csv
validation_subsample: 200
evaluation_tile_dir: data/
save_image_path: snapshots/

#Non-max suppression, threshold for the IoU value to determine when a box should be suppressed.
nms_threshold: 0.5   
