#Config file for DeepMeerkat train.py on HiPerGator

#SlidingWindow
patch_size: 400
patch_overlap: 0.05
rgb_res: 0.1

#Debug plot image
plot_image: False

#Preprocessing routines
preprocess:
          zero_area: True

#Training
training_csvs: /home/b.weinstein/TreeSegmentation/analysis/Results/detection_boxes/SJER/
rgb_tile_dir: /orange/ewhite/NeonData/SJER/DP1.30010.001/2017/FullSite/D17/2017_SJER_2/L3/Camera/Mosaic/V02/
training_images: 10
snapshot: None
batch_size: 3      
epochs: 2
save_snapshot_path: /orange/ewhite/b.weinstein/retinanet/snapshots/
backbone: resnet50
shuffle_training: False

#Evaluation
evaluation_images: 50
evaluation_tile_dir: /orange/ewhite/NeonData/SJER/DP1.30010.001/2017/FullSite/D17/2017_SJER_2/L3/Camera/Mosaic/V02/
save_image_path: /orange/ewhite/b.weinstein/retinanet/snapshots/

#Ground truth
#Path, passed to glob for wildcards
itc_path: /home/b.weinstein/TreeSegmentation/data/ITCs/*/*.shp
itc_tile_path: /home/b.weinstein/TreeSegmentation/data/2017/Camera/L3/

#Non-max suppression, threshold for the IoU value to determine when a box should be suppressed.
nms_threshold: 0.5   
