#Config file for DeepMeerkat train.py on HiPerGator

#Data generation
num_hipergator_workers: 20

#SlidingWindow
patch_size: 400
patch_overlap: 0.05
rgb_res: 0.1

#Preprocessing routines
preprocess:
          zero_area: True

#Hand annotations
hand_annotations: /home/b.weinstein/DeepLidar/data/SJER/training/
retraining_h5_dir: /orange/ewhite/b.weinstein/training_h5s/SJER/handannotation/

#Training
num_GPUs: 1
training_h5_dir: /orange/ewhite/b.weinstein/training_h5s/SJER/
training_csvs: /home/b.weinstein/TreeSegmentation/analysis/Results/detection_boxes/SJER/2018/
rgb_tile_dir: /home/b.weinstein/DeepLidar/data/SJER/training/
training_images: All
weights: /orange/ewhite/b.weinstein/retinanet/snapshots/20190131_145805/resnet50_08.h5
imagenet_weights: False
batch_size: 25      
epochs: 25
save_snapshot_path: /orange/ewhite/b.weinstein/retinanet/snapshots/
backbone: resnet50
shuffle_training: False
score_threshold: 0.20

#Evaluation
evaluation_site: SJER
evaluation_images: 50
evaluation_tile_dir: /home/b.weinstein/DeepLidar/data/SJER/plots/
save_image_path: /orange/ewhite/b.weinstein/retinanet/snapshots/
shuffle_evaluation: False

#For hand annotation neon_MAP
validation_percent: 5

#Non-max suppression, threshold for the IoU value to determine when a box should be suppressed.
nms_threshold: 0.1

#LIDAR
lidar_path: /ufrc/ewhite/b.weinstein/NeonData/SJER/DP1.30003.001/2018/FullSite/D17/2018_SJER_3/L1/DiscreteLidar/ClassifiedPointCloud/
workers: 1
use_multiprocessing: False
max_queue_size: 10
min_density: 100
