#Config file for DeepMeerkat train.py on hypergator

#SlidingWindow
patch_size: 400
patch_overlap: 0.05
rgb_res: 0.1

#Debug plot image
plot_image: False

#Preprocessing routines
preprocess:
          zero_area: True
          NDVI: False
          NDVI_Threshold: 0.1

#Training
training_csvs: /home/b.weinstein/TreeSegmentation/analysis/Results/detection_boxes/HARV/
rgb_tile_dir: /orange/ewhite/NeonData/HARV/DP1.30010.001/2017/FullSite/D01/2017_HARV_4/L3/Camera/Mosaic/V01/

#Number of sliding windows to select
subsample: 5000
snapshot: None
batch_size: 1      
epochs: 10
save_snapshot_path: None
backbone: resnet50
shuffle_training: True
random_transform: True

#Evaluation
evaluation_csvs: /home/b.weinstein/TreeSegmentation/analysis/Results/detection_boxes/HARV/
evaluation_tile_dir: /orange/ewhite/NeonData/HARV/DP1.30010.001/2017/FullSite/D01/2017_HARV_4/L3/Camera/Mosaic/V01/

#Number of sliding windows to select for evaluation
validation_subsample: 50
save_image_path: snapshots/
shuffle_eval: True

#Ground truth
#Path, passed to glob for wildcards
itc_path: /home/b.weinstein/TreeSegmentation/data/ITCs/*/*.shp
itc_tile_path: /home/b.weinstein/TreeSegmentation/data/2017/Camera/L3/

#Non-max suppression, threshold for the IoU value to determine when a box should be suppressed.
nms_threshold: 0.5 
