#Config file for DeepMeerkat train.py on local OSX

#Data generation
num_hipergator_workers: 20

#SlidingWindow
patch_size: 400
patch_overlap: 0.05
rgb_res: 0.1

##Preprocessing routines
preprocess:
          zero_area: True

##Training
training_h5_dir: /Users/Ben/Downloads/
training_csvs: /Users/Ben/Documents/DeepLidar/data/SJER/
rgb_tile_dir: /Users/Ben/Documents/DeepLidar/data/SJER/training/
training_images: All
batch_size: 2   
epochs: 2
imagenet_weights: False
weights: /Users/ben/Documents/DeepLidar/snapshots/SJER_selfsupervised.h5
save_snapshot_path: None
backbone: resnet50
shuffle_training: False
score_threshold: 0.2
num_GPUs: 1

##Retraining
hand_annotations: /Users/ben/Documents/DeepLidar/data/SJER/training/
retraining_h5_dir: /Users/Ben/Downloads/

##Evaluation
evaluation_site: SJER
evaluation_images: All
evaluation_tile_dir: /Users/Ben/Documents/DeepLidar/data/SJER/plots/
save_image_path: snapshots/images/
shuffle_evaluation: False

#Non-max suppression, threshold for the IoU value to determine when a box should be suppressed.
nms_threshold: 0.05

#For hand annotation neon_MAP
validation_percent: 2

#LIDAR
workers: 1
use_multiprocessing: False
max_queue_size: 10
min_density: 100