#Config file for DeepMeerkat train.py on local OSX

#SlidingWindow
patch_size: 400
patch_overlap: 0.05
rgb_res: 0.1

#Preprocessing routines
preprocess:
          zero_area: True

#Training
training_images: 2
training_csvs: data/OSBS/
rgb_tile_dir: data/OSBS/
snapshot: None
batch_size: 1      
epochs: 1
save_snapshot_path: None
backbone: resnet50
shuffle_training: False
single_tile: False

#Evaluation
evaluation_site: OSBS
evaluation_images: 2
evaluation_tile_dir: data/OSBS/
save_image_path: None
shuffle_eval: False

#Ground truth
#Path, passed to glob for wildcards
itc_path: /Users/ben/Documents/TreeSegmentation/data/ITCs/*/*.shp
itc_tile_path: /Users/ben/Documents/TreeSegmentation/data/2017/Camera/L3/

#Non-max suppression, threshold for the IoU value to determine when a box should be suppressed.
nms_threshold: 0.1