#Config file for DeepMeerkat train.py on hypergator

#TODO implementation of sliding window config, currently hardcoded.
#SlidingWindow
patch_size: 250
patch_overlap: 0.05
rgb_res: 0.1

#Debug plot image
plot_image: False

#Preprocessing routines
preprocess:
          zero_area: True
          NDVI: False
          NDVI_Threshold: 0.1

#Training
training_csvs: /home/b.weinstein/TreeSegmentation/analysis/Results/detection_boxes/
rgb_tile_dir: /orange/ewhite/b.weinstein/NEON/D03/OSBS/DP1.30010.001/2017/FullSite/D03/2017_OSBS_3/L3/Camera/Mosaic/V01/
subsample: 5
snapshot: None
batch_size: 1      
epochs: 50
snapshot_path: /orange/ewhite/b.weinstein/retinanet/snapshots/
backbone: resnet101

#Evaluation
evaluation_csvs: data/training/evaluation.csv
validation_subsample: 5
evaluation_tile_dir: data/

