#Config file for DeepMeerkat train.py

#Location of bound box csv
bbox_data_dir: /home/b.weinstein/TreeSegmentation/analysis/Results/bounding_boxes/

#Subsample dataset
subsample: 30000

#Training params
training:
          epochs: 20
          workers: 5

data_generator_params:
          rgb_tile_dir: /orange/ewhite/b.weinstein/NEON/D03/OSBS/DP1.30010.001/2017/FullSite/D03/2017_OSBS_3/L3/Camera/Mosaic/V01/
          batch_size: 32
          shuffle: True

