#Config file for DeepMeerkat train.py on local OSX

#SlidingWindow
patch_size: 400
patch_overlap: 0.05
rgb_res: 0.1

#Preprocessing routines
preprocess:
          zero_area: True

#Training
training_images: All
training_csvs: /Users/ben/Documents/TreeSegmentation/Results/detection_boxes/SJER/2018/NEON_D17_SJER_DP1_262000_4107000_classified_point_cloud_colorized.csv
rgb_tile_dir: /Users/ben/Downloads/
snapshot: None
batch_size: 1      
epochs: 1
save_snapshot_path: None
backbone: resnet50
shuffle_training: False
single_tile: True

#Evaluation
evaluation_site: SJER
evaluation_images: All
evaluation_tile_dir: /Users/ben/Downloads/
save_image_path: None
shuffle_eval: False
validation_percent: 5

#Ground truth
#Path, passed to glob for wildcards
itc_path: /Users/ben/Documents/TreeSegmentation/data/ITCs/*/*.shp
itc_tile_path: /Users/ben/Documents/TreeSegmentation/data/2017/Camera/L3/

#Non-max suppression, threshold for the IoU value to determine when a box should be suppressed.
nms_threshold: 0.1