#Config file for DeepMeerkat train.py on local OSX

#Data generation
num_hipergator_workers: 20
h5_dir: /Users/Ben/Downloads/

#SlidingWindow
patch_size: 400
patch_overlap: 0.05
rgb_res: 0.1

#Preprocessing routines
preprocess:
          zero_area: True

#Training
training_images: All
training_csvs: /Users/Ben/Documents/DeepLidar/data/SJER/plots/
rgb_tile_dir: /Users/Ben/Documents/DeepLidar/data/SJER/plots/
snapshot: None
batch_size: 1   
epochs: 2
imagenet_weights: False
weights: None
save_snapshot_path: None
backbone: resnet50
shuffle_training: False
score_threshold: 0.25
hand_annotations: /Users/ben/Documents/DeepLidar/data/SJER/annotations/2018_SJER_3_315000_4094000_image_crop.xml
num_GPUs: 1

#Evaluation
evaluation_site: SJER
evaluation_images: All
evaluation_tile_dir: /Users/Ben/Documents/DeepLidar/data/SJER/plots/
save_image_path: snapshots/images/
shuffle_evaluation: False

#Non-max suppression, threshold for the IoU value to determine when a box should be suppressed.
nms_threshold: 0.1

#For hand annotation neon_MAP
validation_percent: 100

#LIDAR
lidar_path: /Users/Ben/Documents/DeepLidar/data/SJER/plots/
kernel_size: 15
workers: 1
use_multiprocessing: False
max_queue_size: 10
min_density: 100