theme: jekyll-theme-minimal
num_hipergator_workers: 4
bbox_data_dir: data/
epochs: 100

training_params:
          rgb_tile_dir: /Users/ben/Documents/TreeSegmentation/data/training/
          batch_size: 32
          n_classes: 2
          shuffle: True
