#Config file for DeepMeerkat train.py on HiPerGator

#Data generation
num_hipergator_workers: 25
h5_dir: /orange/ewhite/b.weinstein/training_h5s/TEAK/

#SlidingWindow
patch_size: 400
patch_overlap: 0.05
rgb_res: 0.1

#Preprocessing routines
preprocess:
          zero_area: True

#Training
training_csvs: /home/b.weinstein/TreeSegmentation/analysis/Results/detection_boxes/TEAK/2018/
rgb_tile_dir: /orange/ewhite/NeonData/TEAK/DP3.30010.001/2018/FullSite/D17/2018_TEAK_3/L3/Camera/Mosaic/V01/
training_images: 1000
snapshot: None
batch_size: 6      
epochs: 10
save_snapshot_path: /orange/ewhite/b.weinstein/retinanet/snapshots/
backbone: resnet50
shuffle_training: False
score_threshold: 0.20

#Evaluation
evaluation_site: TEAK
evaluation_images: 50
evaluation_tile_dir: /orange/ewhite/NeonData/TEAK/DP3.30010.001/2018/FullSite/D17/2018_TEAK_3/L3/Camera/Mosaic/V01/
save_image_path: /orange/ewhite/b.weinstein/retinanet/snapshots/
shuffle_evaluation: False

#Non-max suppression, threshold for the IoU value to determine when a box should be suppressed.
nms_threshold: 0.15

#LIDAR
lidar_path: /orange/ewhite/NeonData/TEAK/DP1.30003.001/2018/FullSite/D17/2018_TEAK_3/L1/DiscreteLidar/ClassifiedPointCloud/
kernel_size: 5
workers: 1
use_multiprocessing: False
max_queue_size: 10
