#Config file for DeepMeerkat train.py on local OSX

#SlidingWindow
patch_size: 400
patch_overlap: 0.05
rgb_res: 0.1

#Preprocessing routines
preprocess:
    zero_area: True

#Hand annotations
hand_annotations: /home/b.weinstein/DeepForest/data/SJER/annotations/2017_SJER_2_259000_4110000_image.xml
single_tile: True

#Training
training_images: All
rgb_tile_dir: /home/b.weinstein/DeepForest/data/SJER/
snapshot: /orange/ewhite/b.weinstein/retinanet/snapshots/20181005_134715/resnet50_04.h5
batch_size: 5      
epochs: 15
save_snapshot_path: /orange/ewhite/b.weinstein/retinanet/snapshots/
backbone: resnet50
shuffle_training: True
score_threshold: 0.15

#Non-max suppression, threshold for the IoU value to determine when a box should be suppressed.
nms_threshold: 0.1   

#Evaluation
#Neon site to evaluate
evaluation_site: SJER
validation_percent: 5
evaluation_tile_dir: /home/b.weinstein/DeepForest/data/SJER/
save_image_path: /orange/ewhite/b.weinstein/retinanet/snapshots/

#Ground truth
#Path, passed to glob for wildcards
itc_path: /Users/ben/Documents/TreeSegmentation/data/ITCs/*/*.shp
itc_tile_path: /Users/ben/Documents/TreeSegmentation/data/2017/Camera/L3/
