# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    Python35:
      python.version: '3.5'
steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    conda env create --file=environment.yml
    conda init bash
    eval "$(conda shell.bash hook)"
    conda activate DeepForest
    cd keras_retinanet
    python setup.py build_ext --inplace
  displayName: 'Create Conda environment and build retinanet'

- script: |
    pip install pytest pytest-azurepipelines
    conda activate DeepForest
    pytest
  displayName: 'pytest'

- script: |    
    python setup.py sdist 
  displayName: 'Artifact creation'
- task: CopyFiles@2  
  inputs:    
    targetFolder: $(Build.ArtifactStagingDirectory)

- task: PublishBuildArtifacts@1  
  inputs:    
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'                  
    ArtifactName: 'dist'    
    publishLocation: 'Container'