#Config file for DeepForest

#Train Settings
batch_size: 1
weights: None
backbone: resnet50
image-min-side: 800
multi-gpu: 1
epochs: 1
validation_annotations: None

#Keras generator methods
multiprocessing: False 
workers: 1
max_queue_size: 10

#save snapshot and images
save-snapshot: False

