#Config file for DeepForest

#Train Settings
batch_size: 10
weights: None
backbone: resnet50
image-min-side: 800
multi-gpu: 1
epochs: 1
validation_annotations: None

#save snapshot?
save-snapshot: False