name: DeepForest
channels:
  - defaults
  - conda-forge
dependencies:
  - cython>=0.28
  - h5py
  - matplotlib
  - numpy
  - numpydoc
  - pandas
  - pillow
  - pip
  - progressbar2
  - psutil
  - pyyaml
  - pytest
  - python>3.5
  - recommonmark
  - sphinx
  - sphinx_rtd_theme
  - tqdm
  - twine
  - xmltodict
  - pip:
    - bumpversion
    - keras>= 2.3.0
    - keras-resnet
    - git+git://github.com/bw4sz/keras-retinanet.git
    - opencv-python
    - slidingwindow
    - sphinx-markdown-tables
    - tensorflow==1.14
