name: DeepForest
channels:
  - defaults
dependencies:
  - sphinx
  - pip:
    - cython
    - h5py
    - keras
    - keras-resnet
    - keras-retinanet
    - numpy
    - opencv-python
    - pillow
    - pyyaml
    - scipy

