name: DeepForest
channels:
  - defaults
dependencies:
  - python=3.6
  - sphinx
  - pyyaml
  - cython
  - h5py
  - keras
  - numpy
  - pillow
  - scipy
  - pip
  - pip:
    - keras-resnet
    - opencv-python
