dependencies:
    - python=3.6
    - numpy
    - scipy
    - scikit-learn
    - jupyter
    - keras
    - pandas
    - tensorflow
    - rasterio
    - pip
    - pip:
        - opencv_python
        - comet_ml