name: DeepForest
channels:
  - defaults
dependencies:
  - python=3.6
  - sphinx
  - pyyaml
  - pytest
  - numpydoc
  - cython
  - h5py
  - xmltodict
  - keras
  - tqdm
  - numpy
  - pillow
  - scipy
  - pip
  - matplotlib
  - sphinx_rtd_theme
  - pandas
  - pip:
    - keras-resnet
    - opencv-python
